[workspace]
resolver = "2"
members = ["ai-pipeline/gen", "ai-pipeline/lib", "biscuit", "darkmatter", "model_id", "queue", "research/cli", "research/lib", "schematic/define", "schematic/gen", "sniff/cli", "sniff/lib", "so-you-say", "tabby", "tabby/ui", "tui"]
exclude = ["schematic/schema"]
