[workspace]
resolver = "2"
members = ["ai-pipeline/gen", "ai-pipeline/lib", "api", "api-macros", "md", "model_id", "research/cli", "research/lib", "shared", "sniff/cli", "sniff/lib", "so-you-say", "tabby", "tabby/ui", "tui"]
