[package]
name = "tree-hugger-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hug"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
tree-hugger-lib = { path = "../lib" }
