[package]
name = "so-you-say"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[[bin]]
name = "so-you-say"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
biscuit-speaks = { path = "../biscuit-speaks" }
