[package]
name = "so-you-say"
version = "0.1.0"
edition = "2024"
license = "Parity-7.0.0"

[[bin]]
name = "so-you-say"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
shared = { path = "../shared" }
