[package]
name = "model_id"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["derive", "parsing", "full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "1.0"
